### ISSUE TITLE
Please specify the license for this package

### ISSUE THREAD

**Issue by tarsius** [AndreaOrru/zig-mode#6]
Could you please specify the license used by this package?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the [text of the GPL-3](https://www.gnu.org/licenses/gpl-3.0.txt). But if you only add that file, then the "or (at your option) any later version" bit won't be known.  I recommend that you do *both*.

If this is too noisy for you, then you could also add one of these following lines to the header.  (I do however recommend against doing *only* that - a judge might decide that this is not sufficient.)

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by tarsius** [comment]
Friendly ping! Sorry for being pushy, but it looks like rms is going to request that all unlicensed packages be removed from Melpa, and if I can demonstrate that authors are still acting in response to my requests such as this one, then he might delay that another few weeks, giving the remaining authors more time to act. I think it would be a mistake to remove the unlicensed packages as that has the potential of causing a lot of bad blood.

Thanks a lot!

**Comment by AndreaOrru** [comment]
Sorry @tarsius, I was off the grid for a while. Will do.

**Comment by tarsius** [comment]
Thanks!

I have restored the Melpa recipe.
